apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
    {{- with .Values.helloWorld.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.helloWorld.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.helloWorld.service.type }}
  ports:
  - port: {{ .Values.helloWorld.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
