{{- if .Values.helloworld.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloworld.serviceAccountName" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
  {{- with .Values.helloworld.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helloworld.serviceAccount.automount }}
{{- end }}
