{{- if .Values.helloworld.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: {{ .Values.helloworld.serviceMonitor.team }}
    app.kubernetes.io/instance: {{ .Values.helloworld.serviceMonitor.instance }}
  name: {{ include "helloworld.fullname" . }}
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http
  selector:
    matchLabels:
      {{- include "helloworld.labels" . | nindent 8 }}
{{- end }}
