apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
    {{- with .Values.helloworld.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.helloworld.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.helloworld.service.type }}
  ports:
  - port: {{ .Values.helloworld.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
